- hosts: all
   remote_user: ubuntu
   become: yes
   task: 
   - name: install the latest version of apache
     yum:
       name: httpd
       state: latest
   - name: start service httpd, if not started
     service:
       name: httpd
       state: started
   - name: copy file with owner and permissions
     copy:
       src:/home/ubuntu/index.html
       dest:/var/www/html/index.html
       mode: '777'
