- hosts: webservers
  become: True
  tasks:
    - name: Install packages
      apt:
        name: apache2
        state: present
    - name: Start Apache server
      service:
        name: apache2
        state: started
    - name: Add firewall rules
      ufw:
        rule: allow
        port: 80
        proto: tcp
    - name: Deploy static website
      copy:
        src: "/var/lib/jenkins/workspace/jenkins-2/index.html"
        dest: "/var/www/html/index.html"
        remote_src: yes
