- hosts: webservers
  become: true
  tasks:
    - name: Install packages
      yum:
        name: httpd                   # httpd is the package name for Apache on AWS Linux
        state: present

    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: yes                # Ensure Apache starts on boot

    - name: Add firewall rules
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
